controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

test:
    path: /test/{nom?}
    controller: App\Controller\TestController::index
    defaults:
        nom: 'don man'